tab_spaces = 2
max_width = 100
comment_width = 100

array_horizontal_layout_threshold = 1000
array_width = 80

chain_indent = "Visual"
chain_one_line_max = 80

closure_block_indent_threshold = 1

condense_wildcard_suffixes = true

control_style = "Legacy"

fn_args_layout = "Visual"
fn_call_style = "Visual"
fn_call_width = 80
fn_args_paren_newline = true
fn_args_density = "Compressed"

format_strings = true
wrap_comments = true

generics_indent = "Visual"

match_block_trailing_comma = true

# normalize_comments = true

reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true

single_line_if_else_max_width = 80

# struct_field_align_threshold = 10
# struct_lit_width = 30

use_try_shorthand = true

where_density = "Vertical"
where_style = "Legacy"
