tab_spaces = 2
max_width = 100
comment_width = 80
wrap_comments = true
wrap_match_arms = false

chain_indent = "Visual"
chain_one_line_max = 90
chain_split_single_child = false

reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true

array_width = 100
single_line_if_else_max_width = 100
struct_lit_width = 100
struct_variant_width = 50

fn_call_width = 100
fn_args_density = "Tall"
fn_args_layout = "Visual"

match_block_trailing_comma = true
spaces_around_ranges = true

where_density = "Compressed"
where_style = "Legacy"

closure_block_indent_threshold = 1
