[package]
name = "rustic-mob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "1.0"
regex = "1.5"
walkdir = "2.3"
