######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 9 11:23:00 2008
######################################################################

TEMPLATE = app
TARGET = qpad
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/myChangeButton.h
SOURCES += src/main.cpp src/myChangeButton.cpp
