######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 8 21:27:14 2008
######################################################################

TEMPLATE = app
TARGET = qpad
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myChangeButton.h
SOURCES += main.cpp myChangeButton.cpp
