[package]
name = "ziprecover"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"
log = { version = "0.4.21", features = ["std"] }
rand = "0.8.5"
structopt = "0.3.26"
zip = "2.1.1"
