######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 10 00:14:08 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += counter.h
SOURCES += counter.cpp main.cpp
