all:
	cd src/ && make && echo "Build success."

cairo:
	cd src/ && make cairo && echo "Build success."

opengl:
	cd src/ && make opengl && echo "Build success."

debug:
	cd src/ && make debug

run:
	cd src/ && make run

clean:
	cd src/ && make clean && echo "Cleaned."

count:
	cd src/ && make count
