all:
	cd src/ && make && echo "Build success."

debug:
	cd src/ && make debug && echo "Debug build success."

run:
	cd src/ && make run

clean:
	cd src/ && make clean && echo "Cleaned."

count:
	cd src/ && make count
