include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Clock
Clock_HEADERS = Controller.h
Clock_OBJC_FILES = Controller.m main.m
Clock_RESOURCE_FILES = Clock.plist Clock.gorm
Clock_MAIN_MODEL_FILE = Clock.gorm

include $(GNUSTEP_MAKEFILES)/application.make

