[package]
name = "iced-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["debug", "highlighter", "tokio"] }
rfd = "0.15.3"
tokio = { version = "1.45.0", features = ["fs", "rt"] }
