######################################################################
# Automatically generated by qmake (2.01a) Sun May 11 17:05:07 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
