######################################################################
# Automatically generated by qmake (2.01a) Sat May 9 14:36:36 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/fred/AddressBook/. .

# Input
HEADERS += AddressBook.h
SOURCES += AddressBook.cc main.cc
