######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 26 17:33:41 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
