[package]
name = "route-finder"
version = "0.1.0"
authors = ["Fred Morcos <fred.morcos@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
haversine = "*"
# geo = "*"
structopt = "*"
