CREATE TABLE TEST(id INTEGER, firstname VARCHAR(10), lastname VARCHAR(10));
INSERT INTO TEST VALUES(1,'Christian','Werner');
INSERT INTO TEST VALUES(2,'John','Doe');
INSERT INTO TEST VALUES(3,'Duffy','Duck');
INSERT INTO TEST VALUES(4,'Mickey','Mouse');
INSERT INTO TEST VALUES(5,'Speedy','Gonzales');
