include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = sandbox
sandbox_HEADERS = AppDelegate.h
sandbox_OBJC_FILES = AppDelegate.m main.m
sandbox_RESOURCE_FILES = 

include $(GNUSTEP_MAKEFILES)/application.make

