[package]
name = "rust-reqwest"
version = "0.1.0"
authors = ["Fred Morcos <fred.morcos@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
futures = "0.1.27"
tokio = "0.1.21"
structopt = "0.2.17"
bytes = "0.4.12"
select = "0.4.2"
url = "1.7.2"
env_logger = "0.6.1"
log = "0.4.6"
