[package]
name = "rust-reqwest"
version = "0.1.0"
authors = ["Fred Morcos <fred.morcos@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
futures = "0.1"
tokio = "1.8"
structopt = "0.2"
bytes = "0.4"
select = "0.4"
url = "1.7"
env_logger = "0.6"
log = "0.4"
