[package]
name = "rust-reqwest"
version = "0.1.0"
authors = ["Fred Morcos <fred.morcos@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
futures = "*"
tokio = "*"
structopt = "*"
bytes = "*"
select = "*"
url = "*"
env_logger = "*"
log = "*"
